# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1994a299954c95ce920d5b14884b1f95a6b7e1413e88a4b80b354ad413dae8402777896b36fc6523ac51cdab74d8845fa58600d97b56facdc18539ad331aa4ff

test:
  secret_key_base: c32fd618257112c3f63ac9c119bf9de2e02eed850df5518751d6604c66e543c90f5cc8adef65abc7d2f0bd167a53bc6fb3da0779a0c4c5ad3e7ea11d1585f2d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
